# Generated by Django 6.1.1 on 2026-09-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('quality', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='dashboard.crop')),
            ],
        ),
    ]
